#!/usr/bin/env python3
"""EDA of Project Sidewalk's validator-AI crop datasets and the validator models trained on them.

What it establishes (every number lands in <out>/summary.json and <out>/tables/):
  1. integrity  -- local mirror vs the Hugging Face listing: file count, size, sha256 per image
  2. decode     -- every image opened with PIL: size, mode, corrupt files
  3. tables     -- dir x split x verdict, class x city, Pittsburgh counts, exact duplicates
  4. near-dups  -- 64-bit dHash, Hamming <= --hamming, within and across splits and classes
  5. label-type check -- crop filenames are <city>_<label_id>; joining label_id back to that
                  city's rawLabels says which label type a directory really holds
  6. models     -- config / preprocessor / trainer_state / safetensors header of the five
                  validator models, and the train-set size each trainer_state implies
  7. tagger     -- sidewalk-tagger-ai zips, listed through HTTP range reads of their central
                  directory (a few hundred KB each); nothing is downloaded
  8. montage    -- correct / incorrect samples per directory, for eyeballing

The crop datasets were generated by github.com/ProjectSidewalk/sidewalk-validator-ai
(data_generation.py -> split_data.py -> fine_tune_classifier.py).

usage:
  python src/eda/crops_eda.py
  python src/eda/crops_eda.py --dirs obstacle --skip-models --skip-tagger --out /tmp/x
"""
import argparse, collections, concurrent.futures as cf, hashlib, io, json, os, struct, sys, time
import urllib.request, zipfile

import numpy as np
import pandas as pd
from PIL import Image, ImageDraw

DIRS = ["curbramp", "nocurbramp", "obstacle", "surfaceproblem", "crosswalk"]
EXPECTED_TYPE = {"curbramp": "CurbRamp", "nocurbramp": "NoCurbRamp", "obstacle": "Obstacle",
                 "surfaceproblem": "SurfaceProblem", "crosswalk": "Crosswalk"}
HF = "https://huggingface.co"
DATASET_REPO = "projectsidewalk/sidewalk-validator-ai-dataset-{}"
MODEL_REPO = "projectsidewalk/sidewalk-validator-ai-{}"
PS_RAW = "https://sidewalk-{}.cs.washington.edu/v3/api/rawLabels?filetype=csv"
UA = {"User-Agent": "cmu-10718-sidewalk-eda/1.0"}
# fine_tune_classifier.py: per_device_train_batch_size=8, gradient_accumulation_steps=4
TRAIN_BS, GRAD_ACCUM = 8, 4
TAGGER = {
    "validated": [["Validated/Crosswalk.zip"], ["Validated/CurbRamp.zip"],
                  ["Validated/Obstacle.zip"], ["Validated/SurfaceProblem.zip"]],
    "unvalidated": [["Crosswalk.zip"], ["CurbRamp.z01", "CurbRamp.z02", "CurbRamp.zip"],
                    ["Obstacle.zip"], ["SurfaceProblem.z01", "SurfaceProblem.zip"]],
}


# ----------------------------------------------------------------------------- helpers
def get_json(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120) as r:
        return json.load(r)


def hf_tree(repo, kind="datasets"):
    """Full recursive file listing of a HF repo, following pagination."""
    out, url = [], f"{HF}/api/{kind}/{repo}/tree/main?recursive=true"
    while url:
        with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120) as r:
            out += json.load(r)
            link = r.headers.get("Link") or ""
        url = link.split(";")[0].strip("<> ") if 'rel="next"' in link else None
    return [x for x in out if x["type"] == "file"]


def parse_crop_path(relpath):
    """train/correct/<city>_<label_id>.webp -> (split, verdict, city, label_id)"""
    split, verdict, fn = relpath.split("/")
    city, lid = fn.rsplit(".", 1)[0].rsplit("_", 1)
    return split, verdict, city, int(lid)


def image_features(path):
    """sha256 + full decode + 64-bit dHash for one file. Runs in a worker process."""
    with open(path, "rb") as f:
        data = f.read()
    rec = dict(path=path, bytes=len(data), sha256=hashlib.sha256(data).hexdigest())
    try:
        im = Image.open(io.BytesIO(data))
        fmt = im.format
        im.load()
        rec.update(width=im.width, height=im.height, mode=im.mode, format=fmt, ok=True)
        g = np.asarray(im.convert("L").resize((9, 8), Image.Resampling.LANCZOS), dtype=np.int16)
        bits = (g[:, 1:] > g[:, :-1]).flatten()
        rec["dhash"] = format(int(np.packbits(bits).view(">u8")[0]), "016x")
        rec["mean_luma"] = round(float(np.asarray(im.convert("L")).mean()), 2)
    except Exception as e:  # corrupt / undecodable
        rec.update(ok=False, error=f"{type(e).__name__}: {str(e)[:200]}")
    return rec


def jsonable(o):
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, np.ndarray):
        return o.tolist()
    return str(o)


def crosstab_records(ct):
    """DataFrame crosstab -> {row: {col: n}} with flattened string column names."""
    ct = ct.copy()
    ct.columns = ["/".join(map(str, c)) if isinstance(c, tuple) else str(c) for c in ct.columns]
    return {str(k): {c: int(v) for c, v in row.items()} for k, row in ct.iterrows()}


# ----------------------------------------------------------------------------- HTTP range zip listing
class RangeReader:
    """Random access to a remote file through HTTP Range requests; counts bytes fetched."""

    def __init__(self, url):
        req = urllib.request.Request(url, method="HEAD", headers=UA)
        with urllib.request.urlopen(req, timeout=120) as r:
            self.url, self.size = r.url, int(r.headers["Content-Length"])
        self.fetched = 0

    def read_at(self, start, n):
        end = min(start + n, self.size) - 1
        if end < start:
            return b""
        req = urllib.request.Request(self.url, headers={**UA, "Range": f"bytes={start}-{end}"})
        with urllib.request.urlopen(req, timeout=300) as r:
            d = r.read()
        self.fetched += len(d)
        return d


class _SeekableRange(io.RawIOBase):
    def __init__(self, rr):
        self.rr, self.pos = rr, 0

    def readable(self):
        return True

    def seekable(self):
        return True

    def tell(self):
        return self.pos

    def seek(self, off, whence=0):
        self.pos = off if whence == 0 else self.pos + off if whence == 1 else self.rr.size + off
        return self.pos

    def readinto(self, b):
        d = self.rr.read_at(self.pos, len(b))
        b[:len(d)] = d
        self.pos += len(d)
        return len(d)


def list_zip_central_directory(part_urls):
    """Parse a (possibly split, possibly Zip64) archive's central directory from its last part.

    Returns (entries, bytes_fetched) where entries = [(name, uncompressed, compressed)].
    Split archives (.z01, .z02, ..., .zip) number their disks in that order."""
    parts = [RangeReader(u) for u in part_urls]
    last = parts[-1]
    tail_start = max(0, last.size - 70000)
    tail = last.read_at(tail_start, last.size - tail_start)
    i = tail.rfind(b"PK\x05\x06")
    if i < 0:
        raise ValueError("no end-of-central-directory record")
    _, _, cd_disk, _, total, cd_size, cd_off, _ = struct.unpack("<4sHHHHIIH", tail[i:i + 22])
    if 0xFFFF in (cd_disk, total) or 0xFFFFFFFF in (cd_size, cd_off):
        loc = tail[i - 20:i]
        if loc[:4] != b"PK\x06\x07":
            raise ValueError("zip64 locator missing")
        z64_disk, z64_off, _ = struct.unpack("<IQI", loc[4:])
        rec = parts[z64_disk].read_at(z64_off, 56)
        (_, _, _, _, _, cd_disk, _, total, cd_size, cd_off) = struct.unpack("<4sQHHIIQQQQ", rec)
    cd, disk, off = b"", cd_disk, cd_off
    while len(cd) < cd_size:  # the central directory may itself span parts
        chunk = parts[disk].read_at(off, cd_size - len(cd))
        cd += chunk
        disk, off = disk + 1, 0
    entries, p = [], 0
    while p + 46 <= len(cd) and cd[p:p + 4] == b"PK\x01\x02":
        h = struct.unpack("<4sHHHHHHIIIHHHHHII", cd[p:p + 46])
        csize, usize, fnlen, extlen, cmtlen = h[8], h[9], h[10], h[11], h[12]
        name = cd[p + 46:p + 46 + fnlen].decode("utf-8", "replace")
        extra = cd[p + 46 + fnlen:p + 46 + fnlen + extlen]
        if 0xFFFFFFFF in (usize, csize):  # zip64 extended information extra field
            q = 0
            while q + 4 <= len(extra):
                hid, hlen = struct.unpack("<HH", extra[q:q + 4])
                if hid == 0x0001:
                    vals, r = list(struct.unpack(f"<{hlen // 8}Q", extra[q + 4:q + 4 + 8 * (hlen // 8)])), 0
                    if usize == 0xFFFFFFFF:
                        usize, r = vals[r], r + 1
                    if csize == 0xFFFFFFFF:
                        csize = vals[r]
                    break
                q += 4 + hlen
        entries.append((name, usize, csize))
        p += 46 + fnlen + extlen + cmtlen
    if len(entries) != total:
        print(f"    warning: parsed {len(entries)} central-directory entries, EOCD says {total}", flush=True)
    return entries, sum(pp.fetched for pp in parts)


# ----------------------------------------------------------------------------- sections
def load_listing(dirs):
    rows = []
    for d in dirs:
        for f in hf_tree(DATASET_REPO.format(d)):
            if f["path"].count("/") != 2:
                continue  # .gitattributes
            split, verdict, city, lid = parse_crop_path(f["path"])
            rows.append(dict(dir=d, relpath=f["path"], split=split, verdict=verdict, city=city, label_id=lid,
                             hf_bytes=f["size"], hf_sha256=(f.get("lfs") or {}).get("oid")))
    return pd.DataFrame(rows)


def scan_local(data_root, dirs, workers):
    paths = []
    for d in dirs:
        root = os.path.join(data_root, f"sidewalk-validator-ai-dataset-{d}")
        for dp, dns, fns in os.walk(root):
            dns[:] = [x for x in dns if not x.startswith(".")]
            paths += [(d, os.path.join(dp, fn)) for fn in fns if not fn.startswith(".")]
    t = time.time()
    with cf.ProcessPoolExecutor(max_workers=workers) as ex:
        feats = list(ex.map(image_features, [p for _, p in paths], chunksize=64))
    for (d, p), rec in zip(paths, feats):
        rec["dir"] = d
        rec["relpath"] = os.path.relpath(p, os.path.join(data_root, f"sidewalk-validator-ai-dataset-{d}"))
    print(f"  hashed + decoded {len(feats)} files in {time.time() - t:.0f}s", flush=True)
    return pd.DataFrame(feats).reindex(columns=["dir", "relpath", "path", "bytes", "sha256", "ok", "error", "width",
                                                "height", "mode", "format", "dhash", "mean_luma"])


def near_duplicates(df, hamming):
    """All pairs with dHash Hamming distance <= hamming, chunked brute force (numpy.bitwise_count)."""
    df = df.reset_index(drop=True)
    h = np.array([int(x, 16) for x in df["dhash"]], dtype=np.uint64)
    pairs, B = [], 512
    idx = np.arange(len(h))
    for s in range(0, len(h), B):
        block = h[s:s + B]
        dist = np.bitwise_count(block[:, None] ^ h[None, :])
        ii, jj = np.nonzero((dist <= hamming) & (idx[None, :] > (idx[s:s + B])[:, None]))
        for a, b in zip(ii + s, jj):
            pairs.append((a, b, int(dist[a - s, b])))
    out = []
    for a, b, dd in pairs:
        ra, rb = df.iloc[a], df.iloc[b]
        if ra.dir != rb.dir:
            kind = "cross-class"
        elif ra.split != rb.split:
            kind = "within-class, cross-split"
        else:
            kind = "within-class, same split"
        out.append(dict(kind=kind, hamming=dd, exact=ra.sha256 == rb.sha256,
                        same_city_label=(ra.city, ra.label_id) == (rb.city, rb.label_id),
                        a=f"{ra.dir}/{ra.relpath}", b=f"{rb.dir}/{rb.relpath}",
                        a_verdict=ra.verdict, b_verdict=rb.verdict,
                        verdict_conflict=(ra.dir == rb.dir and ra.verdict != rb.verdict)))
    return pd.DataFrame(out, columns=["kind", "hamming", "exact", "same_city_label", "a", "b",
                                      "a_verdict", "b_verdict", "verdict_conflict"])


def fetch_bytes(url, tries=4):
    """Whole-body GET with retries -- the Project Sidewalk servers drop long responses now and then."""
    for attempt in range(tries):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=600) as r:
                return r.read()
        except Exception as e:
            if attempt == tries - 1:
                raise
            print(f"  retry {attempt + 1} {url}: {type(e).__name__}", flush=True)
            time.sleep(10 * (attempt + 1))


def label_type_check(listing, pgh_labels, cities):
    cols = ["label_id", "label_type", "severity", "agree_count", "disagree_count"]
    frames = []
    for city in ["pittsburgh", *cities]:
        src = pgh_labels if city == "pittsburgh" and os.path.exists(pgh_labels) else PS_RAW.format(city.replace("_", "-"))
        try:
            raw = pd.read_csv(src if os.path.exists(src) else io.BytesIO(fetch_bytes(src)), usecols=cols)
        except Exception as e:
            print(f"  label check: could not read {src}: {e}", flush=True)
            continue
        m = listing[listing.city == city].merge(raw, on="label_id", how="left")
        m["source"] = src
        frames.append(m)
    if not frames:
        return None, None
    m = pd.concat(frames, ignore_index=True)
    m["label_type"] = m["label_type"].fillna("<not in live API>")
    m["matches_dir"] = m["label_type"] == m["dir"].map(EXPECTED_TYPE)
    ct = pd.crosstab([m.city, m.dir], m.label_type)
    return m, ct


def safetensors_header(path_or_url):
    """Tensor count / parameter count / dtypes from the JSON header only -- no weights loaded.
    Works on a local file or, through two HTTP range reads, on a remote one."""
    if os.path.exists(path_or_url):
        with open(path_or_url, "rb") as f:
            n = struct.unpack("<Q", f.read(8))[0]
            hdr = json.loads(f.read(n))
    else:
        rr = RangeReader(path_or_url)
        n = struct.unpack("<Q", rr.read_at(0, 8))[0]
        hdr = json.loads(rr.read_at(8, n))
    hdr.pop("__metadata__", None)
    params = sum(int(np.prod(v["shape"])) for v in hdr.values())
    dtypes = collections.Counter(v["dtype"] for v in hdr.values())
    return dict(tensors=len(hdr), params=params, dtypes=dict(dtypes))


def model_section(models_root, listing):
    out = {}
    for d in DIRS:
        repo = MODEL_REPO.format(d)
        local = os.path.join(models_root, f"sidewalk-validator-ai-{d}")

        def load(name):
            p = os.path.join(local, name)
            if os.path.exists(p):
                return json.load(open(p))
            return get_json(f"{HF}/{repo}/resolve/main/{name}")

        cfg, pp, ts = load("config.json"), load("preprocessor_config.json"), load("trainer_state.json")
        evals = [h for h in ts["log_history"] if "eval_macro_f1" in h]
        steps_per_epoch = (evals[1]["step"] - evals[0]["step"]) if len(evals) > 1 else None
        # HF Trainer: optimizer steps/epoch = ceil(ceil(N / bs) / accum)  =>  N in (lo, hi]
        implied = None
        if steps_per_epoch:
            implied = [(steps_per_epoch - 1) * GRAD_ACCUM * TRAIN_BS + 1, steps_per_epoch * GRAD_ACCUM * TRAIN_BS]
        published_train = int(((listing.dir == d) & (listing.split == "train")).sum()) if len(listing) else None
        tree = {f["path"]: f for f in hf_tree(repo, "models")}
        st = os.path.join(local, "model.safetensors")
        rec = dict(
            hf_repo=f"{HF}/{repo}", hf_commit=get_json(f"{HF}/api/models/{repo}").get("sha"),
            architecture=cfg.get("architectures"), model_type=cfg.get("model_type"),
            hidden_size=cfg.get("hidden_size"), num_hidden_layers=cfg.get("num_hidden_layers"),
            config_image_size=cfg.get("image_size"), patch_size=cfg.get("patch_size"),
            id2label=cfg.get("id2label"), transformers_version=cfg.get("transformers_version"),
            preprocessor=dict(type=pp.get("image_processor_type"), size=pp.get("size"),
                              crop_size=pp.get("crop_size"), mean=pp.get("image_mean"), std=pp.get("image_std")),
            best_model_checkpoint=ts.get("best_model_checkpoint"), best_val_macro_f1=ts.get("best_metric"),
            epoch_at_checkpoint=ts.get("epoch"), global_step=ts.get("global_step"), max_steps=ts.get("max_steps"),
            num_train_epochs=ts.get("num_train_epochs"),
            val_macro_f1_by_epoch=[round(h["eval_macro_f1"], 4) for h in evals],
            val_loss_by_epoch=[round(h["eval_loss"], 4) for h in evals],
            optimizer_steps_per_epoch=steps_per_epoch, implied_train_images_range=implied,
            published_train_split_images=published_train,
            implied_matches_published=(implied is not None and published_train is not None
                                       and implied[0] <= published_train <= implied[1]),
            weights_sha256=(tree.get("model.safetensors", {}).get("lfs") or {}).get("oid"),
            weights_bytes=tree.get("model.safetensors", {}).get("size"),
            local_files=sorted(os.listdir(local)) if os.path.isdir(local) else None,
        )
        rec["safetensors"] = safetensors_header(st if os.path.exists(st) else f"{HF}/{repo}/resolve/main/model.safetensors")
        if os.path.isdir(local):  # verify whatever has landed locally against the HF listing
            chk = {}
            for name, f in tree.items():
                p = os.path.join(local, name)
                if not os.path.exists(p):
                    chk[name] = "missing"
                elif os.path.getsize(p) != f["size"]:
                    chk[name] = f"size {os.path.getsize(p)} != {f['size']}"
                elif name == "model.safetensors":
                    h = hashlib.sha256()
                    with open(p, "rb") as fh:
                        while blk := fh.read(1 << 24):
                            h.update(blk)
                    chk[name] = "sha256 ok" if h.hexdigest() == rec["weights_sha256"] else "SHA256 MISMATCH"
                else:
                    chk[name] = "size ok"
            rec["local_verification"] = chk
        out[d] = rec
    shas = {d: r["weights_sha256"] for d, r in out.items()}
    return out, dict(distinct_weight_files=len(set(shas.values())), sha256=shas)


def tagger_section():
    out = {}
    for group, archives in TAGGER.items():
        repo = f"projectsidewalk/sidewalk-tagger-ai-{group}"
        base = f"{HF}/datasets/{repo}/resolve/main/"
        for parts in archives:
            key = f"{group}/{parts[-1]}"
            try:
                entries, fetched = list_zip_central_directory([base + p for p in parts])
            except Exception as e:
                out[key] = dict(error=f"{type(e).__name__}: {e}")
                print(f"  tagger {key}: {e}", flush=True)
                continue
            files = [e for e in entries if not e[0].endswith("/")]
            ext = collections.Counter(e[0].rsplit(".", 1)[-1].lower() for e in files)
            csvs = [e[0] for e in files if e[0].endswith(".csv")]
            # crop filenames are <source>-<city>-<label_id>-<LabelType>.png, e.g. gsv-pittsburgh-761-CurbRamp.png
            city = collections.Counter(e[0].split("/")[-1].split("-")[1] for e in files
                                       if e[0].endswith(".png") and e[0].split("/")[-1].count("-") >= 3)
            rec = dict(hf=f"{HF}/datasets/{repo}", parts=parts, entries=len(files), by_extension=dict(ext),
                       by_city=dict(city.most_common()), pittsburgh_images=city.get("pittsburgh", 0),
                       images=sum(n for x, n in ext.items() if x in ("png", "jpg", "jpeg", "webp")),
                       uncompressed_gb=round(sum(e[1] for e in files) / 1e9, 2), csv_members=csvs,
                       central_directory_bytes_fetched=fetched)
            if len(parts) == 1 and csvs:  # single-part archive: read the (small) tag CSVs too
                rr = RangeReader(base + parts[0])
                z = zipfile.ZipFile(io.BufferedReader(_SeekableRange(rr), buffer_size=1 << 20))
                rec["csv"] = {}
                for c in csvs:
                    t = pd.read_csv(io.BytesIO(z.read(c)))
                    tagcols = [x for x in t.columns if set(pd.unique(t[x].dropna())) <= {0, 1}]
                    rec["csv"][c] = dict(rows=len(t), columns=list(t.columns)[:8] + (["..."] if len(t.columns) > 8 else []),
                                         tag_positives={x: int(t[x].sum()) for x in tagcols})
                rec["central_directory_bytes_fetched"] += rr.fetched
            out[key] = rec
            print(f"  tagger {key}: {rec['images']} images, {rec['uncompressed_gb']} GB uncompressed", flush=True)
    return out


def montage(feats, data_root, out_png, per_correct=6, per_incorrect=3, tile=160, seed=0):
    rng = np.random.default_rng(seed)
    rows = []
    for d in DIRS:
        sub = feats[(feats.dir == d) & feats.ok]
        if not len(sub):
            continue
        pick = []
        for v, k in [("correct", per_correct), ("incorrect", per_incorrect)]:
            s = sub[sub.verdict == v]
            pick += [(v, r) for _, r in s.iloc[rng.choice(len(s), min(k, len(s)), replace=False)].iterrows()]
        rows.append((d, pick))
    label_w = 170
    W, H = label_w + tile * (per_correct + per_incorrect), (tile + 18) * len(rows)
    canvas = Image.new("RGB", (W, H), "white")
    draw = ImageDraw.Draw(canvas)
    for ri, (d, pick) in enumerate(rows):
        y = ri * (tile + 18)
        name = f"{d}/\n(== crosswalk bytes)" if d == "curbramp" else f"{d}/"
        draw.text((6, y + tile // 2 - 10), name, fill="black")
        for ci, (v, r) in enumerate(pick):
            im = Image.open(os.path.join(data_root, f"sidewalk-validator-ai-dataset-{d}", r.relpath)).convert("RGB")
            im.thumbnail((tile, tile))
            x = label_w + ci * tile
            canvas.paste(im, (x, y))
            draw.text((x + 2, y + tile + 2), f"{v[:3]} {r.city}", fill="green" if v == "correct" else "red")
    canvas.save(out_png)


def pair_montage(pairs, data_root, out_png, n=10, tile=180):
    sel = pairs[pairs.kind != "within-class, same split"].sort_values("hamming").head(n)
    if not len(sel):
        return 0
    canvas = Image.new("RGB", (tile * 2 + 10, (tile + 30) * len(sel)), "white")
    draw = ImageDraw.Draw(canvas)
    for i, (_, p) in enumerate(sel.iterrows()):
        y = i * (tile + 30)
        for j, key in enumerate(["a", "b"]):
            d, rel = p[key].split("/", 1)
            im = Image.open(os.path.join(data_root, f"sidewalk-validator-ai-dataset-{d}", rel)).convert("RGB")
            im.thumbnail((tile, tile))
            canvas.paste(im, (j * (tile + 10), y))
        draw.text((2, y + tile + 2), f"{p.kind} h={p.hamming} exact={p.exact}", fill="black")
        draw.text((2, y + tile + 14), f"{p.a.split('/')[-1]} | {p.b.split('/')[-1]}", fill="black")
    canvas.save(out_png)
    return len(sel)


# ----------------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-root", default="/data/datasets")
    ap.add_argument("--models-root", default="/data/datasets/models")
    ap.add_argument("--pgh-labels", default="/data/datasets/pittsburgh/projectsidewalk/rawLabels.csv")
    ap.add_argument("--verify-cities", default="teaneck,oradell",
                    help="extra cities whose live rawLabels are joined to crop label_ids")
    ap.add_argument("--out", default="/data/eda/crops")
    ap.add_argument("--dirs", default=",".join(DIRS))
    ap.add_argument("--workers", type=int, default=16)
    ap.add_argument("--hamming", type=int, default=4)
    ap.add_argument("--skip-models", action="store_true")
    ap.add_argument("--skip-tagger", action="store_true")
    a = ap.parse_args()
    dirs = a.dirs.split(",")
    tables, figs = os.path.join(a.out, "tables"), os.path.join(a.out, "figures")
    os.makedirs(tables, exist_ok=True)
    os.makedirs(figs, exist_ok=True)
    S = dict(generated_at=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), args=vars(a))

    # 1. listing + local scan + integrity
    print("[1] HF listing + local hash/decode", flush=True)
    listing = load_listing(dirs)
    S["hf_dataset_commits"] = {d: get_json(f"{HF}/api/datasets/{DATASET_REPO.format(d)}").get("sha") for d in dirs}
    feats = scan_local(a.data_root, dirs, a.workers)
    m = listing.merge(feats, on=["dir", "relpath"], how="outer", indicator=True)
    both = m[m._merge == "both"]
    integ = {}
    for d in dirs:
        md = m[m.dir == d]
        b = md[md._merge == "both"]
        integ[d] = dict(hf_files=int((md._merge != "right_only").sum()), local_files=int((md._merge != "left_only").sum()),
                        missing_locally=int((md._merge == "left_only").sum()), extra_locally=int((md._merge == "right_only").sum()),
                        size_mismatch=int((b.hf_bytes != b.bytes).sum()), sha256_mismatch=int((b.hf_sha256 != b.sha256).sum()),
                        sha256_verified=int((b.hf_sha256 == b.sha256).sum()),
                        hf_gb=round(md.hf_bytes.sum() / 1e9, 3), local_gb=round(md.bytes.sum() / 1e9, 3))
    S["integrity"] = integ
    S["integrity_all_verified"] = all(v["missing_locally"] == v["extra_locally"] == v["size_mismatch"]
                                      == v["sha256_mismatch"] == 0 for v in integ.values())
    if {"curbramp", "crosswalk"} <= set(dirs):
        cr = feats[feats.dir == "curbramp"].set_index("relpath").sha256
        cw = feats[feats.dir == "crosswalk"].set_index("relpath").sha256
        common = cr.index.intersection(cw.index)
        S["curbramp_vs_crosswalk_bytes"] = dict(curbramp_files=len(cr), crosswalk_files=len(cw), same_paths=len(common),
                                                identical_sha256=int((cr[common] == cw[common]).sum()),
                                                only_in_curbramp=sorted(set(cr.index) - set(cw.index)),
                                                only_in_crosswalk=sorted(set(cw.index) - set(cr.index)))
    print(f"  integrity all verified: {S['integrity_all_verified']}", flush=True)

    # 2. decode
    feats = feats.merge(listing[["dir", "relpath", "split", "verdict", "city", "label_id"]], on=["dir", "relpath"], how="left")
    ok = feats[feats.ok == True]  # noqa: E712
    S["decode"] = dict(files=len(feats), decoded_ok=len(ok), corrupt=feats.loc[feats.ok != True, ["dir", "relpath", "error"]].to_dict("records"),
                       formats=dict(collections.Counter(ok.format)), modes=dict(collections.Counter(ok["mode"])),
                       square_640=int(((ok.width == 640) & (ok.height == 640)).sum()),
                       max_side_640=int((ok[["width", "height"]].max(axis=1) == 640).sum()),
                       non_square=int((ok.width != ok.height).sum()),
                       bytes_median_kb=round(ok.bytes.median() / 1e3, 1))
    sizes = ok.groupby(["width", "height"]).size().sort_values(ascending=False).rename("n").reset_index()
    sizes.to_csv(os.path.join(tables, "image_sizes.csv"), index=False)
    S["decode"]["top_sizes"] = sizes.head(15).to_dict("records")
    short = ok[["width", "height"]].min(axis=1)
    hist, edges = np.histogram(short, bins=[0, 100, 200, 300, 400, 500, 600, 639, 640])
    S["decode"]["short_side_histogram"] = dict(edges=edges.tolist(), counts=hist.tolist())
    feats.drop(columns=["path"]).to_csv(os.path.join(tables, "image_features.csv.gz"), index=False)

    # 3. tables
    print("[3] tables", flush=True)
    svd = pd.crosstab(listing.dir, [listing.split, listing.verdict], margins=True)
    svd.to_csv(os.path.join(tables, "dir_split_verdict.csv"))
    S["dir_split_verdict"] = crosstab_records(svd)
    real = listing[listing.dir != "curbramp"]  # curbramp/ is a byte copy of crosswalk/
    S["real_classes"] = sorted(real.dir.unique())
    S["correct_by_real_class"] = real[real.verdict == "correct"].dir.value_counts().to_dict()
    S["all_by_real_class"] = real.dir.value_counts().to_dict()
    cc = S["correct_by_real_class"]
    S["correct_imbalance_max_over_min"] = round(max(cc.values()) / min(cc.values()), 2) if cc else None
    for tag, sub in [("correct", real[real.verdict == "correct"]), ("all", real)]:
        ct = pd.crosstab(sub.city, sub.dir, margins=True).sort_values("All", ascending=False)
        ct.to_csv(os.path.join(tables, f"city_by_class_{tag}.csv"))
        S[f"city_by_class_{tag}"] = crosstab_records(ct)
    pgh = listing[listing.city == "pittsburgh"]
    pct = pd.crosstab(pgh.dir, [pgh.split, pgh.verdict], margins=True)
    pct.to_csv(os.path.join(tables, "pittsburgh_dir_split_verdict.csv"))
    S["pittsburgh"] = dict(table=crosstab_records(pct), real_class_images=int((pgh.dir != "curbramp").sum()),
                           real_class_correct=int(((pgh.dir != "curbramp") & (pgh.verdict == "correct")).sum()),
                           share_of_real_images=round((pgh.dir != "curbramp").sum() / max(len(real), 1), 4))
    cs = pd.crosstab([real.dir, real.city], real.split, normalize="index").round(3)
    cs["n"] = real.groupby(["dir", "city"]).size()
    cs.to_csv(os.path.join(tables, "city_split_share.csv"))
    S["cities_missing_a_split"] = [f"{d}/{c}" for (d, c), r in cs.iterrows()
                                   if min(r.get("train", 0), r.get("val", 0), r.get("test", 0)) == 0 and r.n >= 10]
    S["n_cities"] = int(real.city.nunique())
    S["cities"] = sorted(real.city.unique())

    # exact duplicates by content (excluding the curbramp/ copy)
    fr = feats[feats.dir != "curbramp"]
    g = fr.groupby("sha256")
    dup = fr[fr.sha256.map(g.size()) > 1].sort_values("sha256")
    dup[["sha256", "dir", "split", "verdict", "relpath"]].to_csv(os.path.join(tables, "exact_duplicates.csv"), index=False)
    groups = [grp for _, grp in dup.groupby("sha256")]
    S["exact_duplicates"] = dict(
        groups=len(groups),
        cross_split_within_class=[grp[["dir", "relpath"]].to_dict("records") for grp in groups
                                  if grp.dir.nunique() == 1 and grp.split.nunique() > 1],
        cross_class=[grp[["dir", "relpath"]].to_dict("records") for grp in groups if grp.dir.nunique() > 1],
        verdict_conflicts=[grp[["dir", "relpath"]].to_dict("records") for grp in groups
                           if grp.dir.nunique() == 1 and grp.verdict.nunique() > 1])

    # 4. near-duplicates
    print("[4] near-duplicates (dHash)", flush=True)
    nd_in = fr[fr.ok == True]  # noqa: E712
    degenerate = nd_in.dhash.isin(["0000000000000000", "ffffffffffffffff"])
    pairs = near_duplicates(nd_in[~degenerate], a.hamming)
    pairs.to_csv(os.path.join(tables, "near_duplicate_pairs.csv"), index=False)
    S["near_duplicates"] = dict(
        method=f"64-bit dHash (9x8 grayscale LANCZOS), Hamming <= {a.hamming}; curbramp/ excluded; "
               f"{int(degenerate.sum())} degenerate hashes (all-0/all-1) excluded",
        images_compared=int((~degenerate).sum()), pairs=len(pairs),
        by_kind=pairs.groupby(["kind", "exact"]).size().rename("n").reset_index().to_dict("records") if len(pairs) else [],
        verdict_conflicts=int(pairs.verdict_conflict.sum()) if len(pairs) else 0,
        cross_split_images_involved=int(len(set(pairs.loc[pairs.kind == "within-class, cross-split", "a"])
                                            | set(pairs.loc[pairs.kind == "within-class, cross-split", "b"]))) if len(pairs) else 0)
    S["near_duplicates"]["montage_pairs"] = pair_montage(pairs, a.data_root, os.path.join(figs, "near_duplicate_pairs.png"))

    # 5. label-type check
    print("[5] label-type check against rawLabels", flush=True)
    lt, ct = label_type_check(listing, a.pgh_labels, [c for c in a.verify_cities.split(",") if c])
    if lt is not None:
        ct.to_csv(os.path.join(tables, "label_type_check.csv"))
        agg = lt.groupby("dir").agg(crops_checked=("label_id", "size"), matches_dir_name=("matches_dir", "sum"))
        agg["types_found"] = lt.groupby("dir").label_type.agg(lambda s: dict(collections.Counter(s)))
        S["label_type_check"] = dict(cities=sorted(lt.city.unique()), by_dir=json.loads(agg.to_json(orient="index")),
                                     table=crosstab_records(ct))
        lt["net_agree"] = lt.agree_count - lt.disagree_count
        S["label_type_check"]["net_agree_today_by_verdict"] = json.loads(
            lt.groupby(["verdict"]).net_agree.describe()[["count", "min", "50%", "max"]].to_json(orient="index"))
        pl = lt[(lt.city == "pittsburgh") & (lt.dir != "curbramp")]
        S["pittsburgh"]["severity_of_crops_today"] = json.loads(
            pd.crosstab([pl.dir, pl.verdict], pl.severity.fillna(-1).astype(int)).to_json(orient="index"))

    # 6. models
    if not a.skip_models:
        print("[6] validator models", flush=True)
        S["models"], S["model_weights"] = model_section(a.models_root, listing)
        pd.DataFrame([dict(dir=d, best_val_macro_f1=r["best_val_macro_f1"], epoch=r["epoch_at_checkpoint"],
                           steps_per_epoch=r["optimizer_steps_per_epoch"], implied_lo=(r["implied_train_images_range"] or [None])[0],
                           implied_hi=(r["implied_train_images_range"] or [None, None])[1],
                           published_train=r["published_train_split_images"], match=r["implied_matches_published"],
                           params=(r.get("safetensors") or {}).get("params"))
                      for d, r in S["models"].items()]).to_csv(os.path.join(tables, "validator_models.csv"), index=False)

    # 7. tagger
    if not a.skip_tagger:
        print("[7] sidewalk-tagger-ai archives (central directory only)", flush=True)
        S["tagger"] = tagger_section()

    # 8. montage
    montage(feats, a.data_root, os.path.join(figs, "crops_montage.png"))

    with open(os.path.join(a.out, "summary.json"), "w") as f:
        json.dump(S, f, indent=1, default=jsonable)
    print(f"wrote {a.out}/summary.json", flush=True)


if __name__ == "__main__":
    sys.exit(main())
